services:
  - type: web
    name: surgecart-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_ORIGIN
        value: https://surgecart-client.onrender.com
      - key: MONGO_URI
        sync: false

  - type: web
    name: surgecart-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://surgecart-api.onrender.com
